u_x = float(input("Enter x-coordinate of the first vector: "))
u_y = float(input("Enter y-coordinate of the first vector: "))
v_x = float(input("Enter x-coordinate of the second vector: "))
v_y = float(input("Enter y-coordinate of the second vector: "))
print("Inner product is: " + str(u_x * v_x + u_y * v_y))